version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-west-2:695292474035:task-definition/task-nginx:9"
        LoadBalancerInfo:
          ContainerName: "nginx"
          ContainerPort: 80